default:
  image: maven:3.8.3-jdk-11
  tags:
    - fif-runner
variables:
  TAGS:
    value: '@release and @qa'
    description: 'An specific gherkin tag to use when tagging.'
stages:
  - test
test:
  stage: test
  script:
    - mvn clean test
